### ISSUE TITLE
Text under cursor is not visible

### ISSUE THREAD

**Issue by rpopic2** [ng-hai/rose-pine-blinksh#1]
Hi, I found that cursor hides the text beneath as follows :
![D72187FE-E301-42B1-AAD7-7A3CBF25A3F8](https://user-images.githubusercontent.com/8055265/167436601-8870c66d-30d6-44b7-84af-d0f67ffc2ced.jpeg)
![EC93F42C-514A-4969-B569-F67A6CCC65A0](https://user-images.githubusercontent.com/8055265/167436593-fb76d53c-c321-4fed-a516-8840ac4cc983.jpeg)
![50F91357-ADB6-4231-996C-28F5E2062886](https://user-images.githubusercontent.com/8055265/167436730-88c7f134-6493-42bb-a904-2df6c2070843.jpeg)
Applying any rose pine theme will reproduce this issue.
Current workaround would be changing cursor colour manually.

**Comment by rpopic2** [comment]
this was caused by the alpha value of the cursor. It was not set to 0.5.
here is my fix on gist :
https://gist.github.com/rpopic2/7ef18dd37590fe49146e1785cc7243d2
I’ll work on other versions and pr tommorow..

**Comment by ng-hai** [comment]
You could refer from this site, and adjust the alpha value base on current `inactive` or `highlight` color
https://rosepinetheme.com/palette
